## Python数据分析

### 第二章 Numpy基础
- 数据类型
- 数组类型
- 类型转换
- 创建数组
- 数组索引
- 数组切片
- 改变维度

In [1]:
def pythonsum(n):
  a = range(n)
  b = range(n)
  c = []
  
  for i in range(len(a)):
    a[i] = i ** 2
    b[i] = i ** 3
    c.append(a[i] + b[i])
    
  return c

In [2]:
def numpysum(n):
  a = numpy.arange(n) ** 2
  b = numpy.arange(n) ** 3
  c = a + b
  return c

#### 2.1 Numpy数组对象

ndarray多维数组对象：实际的数据 + 描述数据的元数据


In [40]:
# 使用arange()函数创建数组，并获取其数据类型：
import numpy

a = np.arange(5)
a.dtype    # dtype('int64')

dtype('int64')

In [41]:
# 创建一个向量（一维Numpy数组），并确定其向量的维度：
a
np.array([0, 1, 2, 3, 4])
# 数组的shape属性返回一个元组(tuple)
a.shape    # (5,)

(5,)

#### 2.2 实践：创建多维数组

In [12]:
# 创建一个多维数组，并显示其维度：
# np.arange()函数创建的数组作为列表元素，np.array()函数创建2 * 2的数组
m = np.array([np.arange(2), np.arange(2)])
m

array([[0, 1],
       [0, 1]])

In [13]:
 m.shape

(2, 2)

In [17]:
# 创建一个3*3的多维数组
b = np.array([np.arange(3), np.arange(3), np.arange(3)])
b

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [18]:
b.shape

(3, 3)

##### 一、选取数组元素

In [20]:
# 选取数组中的某个特定元素
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [21]:
a[0, 0]

1

In [24]:
a[0, 1]

2

In [26]:
a[1, 0]

3

In [27]:
a[1, 1]

4

In [ ]:
##### 二、Numpy数据类型

In [29]:
np.float64(42)

42.0

In [33]:
np.int8(42.0)

NameError: name 'int8' is not defined

In [32]:
bool(42)

True

In [34]:
bool(0)

False

In [35]:
bool(42.0)

True

In [36]:
float(True)

1.0

In [37]:
float(False)

0.0

In [46]:
np.arange(7, dtype = np.uint16)

array([0, 1, 2, 3, 4, 5, 6], dtype=uint16)

In [47]:
# 将浮点数转换为复数，反之不行，触发TypeError：
complex(1.0)

(1+0j)

In [48]:
float(1+0j)

TypeError: float() argument must be a string or a real number, not 'complex'

##### 三、数据类型对象
数据类型对象给出单个数组元素在内存中占用的字节数，dtype的itemsize属性：

numpy.dtype

In [49]:
a.dtype.itemsize

8

##### 四、字符编码

![](http://www.shminger.cn:3380/images/2024/04/28/202404282229978.png)

注：在Numpy中优先使用dtype对象表示数据类型

In [51]:
# 创建一个单精度浮点数数组：
np.arange(7, dtype = 'f')

array([0., 1., 2., 3., 4., 5., 6.], dtype=float32)

In [53]:
# 创建一个复数数组：
np.arange(7, dtype = 'D')

array([0.+0.j, 1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j])